In [1]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from dash import Dash, dcc, html, Input, Output

In [2]:
euro_usd = pd.read_excel('/Users/emilka/Desktop/Studia/wyrównawczy/euro_usd.xlsx')
euro_usd.head()

        Data  eur/pln_o  eur/pln_z  usd/pln_o  usd/pln_z  eur_stopa  usd_stopa
0 2018-01-01     4.1777     4.1547     3.4808     3.3449   0.550542   3.904275
1 2018-02-01     4.1552     4.1759     3.3451     3.4245  -0.498171  -2.373621
2 2018-03-01     4.1766     4.2172     3.4251     3.4223  -0.972083   0.081749
3 2018-04-01     4.2171     4.2381     3.4217     3.5088  -0.497973  -2.545518
4 2018-05-01     4.2382     4.3162     3.5086     3.6915  -1.840404  -5.212905

In [3]:
euro_usd = euro_usd.iloc[:,[0,5,6]]

In [4]:
euro_usd = euro_usd.rename(columns={'eur_stopa':'EUR/PLN', 'usd_stopa':'USD/PLN'})
euro_usd.head()

        Data   EUR/PLN   USD/PLN
0 2018-01-01  0.550542  3.904275
1 2018-02-01 -0.498171 -2.373621
2 2018-03-01 -0.972083  0.081749
3 2018-04-01 -0.497973 -2.545518
4 2018-05-01 -1.840404 -5.212905

In [5]:
external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']
colors = {
    'background': '#111111',
    'text': 'MediumPurple',
    'text2': 'Thistle'
}

def years(self):
        return [{"label": self.years[i], "value": i} for i in range(len(self.years))]

app = Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div(style={'backgroundColor': colors['background']}, 
    children=[
        html.Div(
            className="row",
            children=[
                html.Div(
                    className="four columns div-user-controls",
                    children=[
                        html.H2("DASH - stopy strat akcji", style={
            'textAlign': 'center',
            'color': colors['text']
        }),
                        html.P("""Wizualizacja szeregu czasowego z Plotly - Dash""", style={
            'textAlign': 'center',
            'color': colors['text']
        }),
                        html.P("""Wybierz z listy akcje, które chcesz zobaczyć.""", style={
            'textAlign': 'center',
            'color': colors['text']
        }),
                    ],
                ),
                html.Div(
                    className="eight columns div-for-charts bg-grey",
                    children=[
                        
      dcc.Graph(id="time_series"
             ),
                        
      dcc.Checklist(
        id='stock',
        options=[{"label": x, "value": x} 
                 for x in euro_usd.columns[1:]],
        value=[euro_usd.columns[1], euro_usd.columns[2]],
        style={"color":"White"},
        labelStyle={'display': 'inline-block'}
    ),

                                               
    
                    ],
                ),
            ],
        )                        
    ]
)

        
        
@app.callback(
    Output("time_series", "figure"), 
    [Input("stock", "value")])

def display_time_series(stock):
    fig = px.line(euro_usd, x='Data', y=stock, hover_data={"Data": "|%B %d, %Y"},
                  title='Stopy strat EUR/PLN i USD/PLN w latach 2018-2020')

    fig.update_layout({"plot_bgcolor": "rgba(1, 1, 1, 1)", "paper_bgcolor": "rgba(1, 1, 1, 1)", 'font':{
                    'color': colors['text2']}})
    fig.update_yaxes(title='Stopy strat')
    fig.update_xaxes(dtick="M2",tickformat="%b\n%Y", rangeslider_visible=True,
        rangeselector=dict(
        buttons=list([
            dict(count=1, label="1m", step="month", stepmode="backward"),
            dict(count=6, label="6m", step="month", stepmode="backward"),
            dict(count=1, label="YTD", step="year", stepmode="todate"),
            dict(count=1, label="1y", step="year", stepmode="backward"),
            dict(step="all")
        ])
    ))
    return fig

if __name__ == '__main__':
    app.run_server(debug=False)

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Jan/2022 12:37:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Jan/2022 12:37:34] "GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Jan/2022 12:37:36] "GET /_favicon.ico?v=2.0.0 HTTP/1.1" 200 -
127.0.0.1 - - [29/Jan/2022 12:37:36] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [29/Jan/2022 12:37:36] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [29/Jan/2022 12:37:36] "GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1" 200 -
127.0.0.1 - - [29/Jan/2022 12:37:38] "POST /_dash-update-component HTTP/1.1" 200 -